### PR TITLE
Reflect changes in VM creation in the portal

### PR DESCRIPTION
**Pull request by akrause2014**
# EIDF Documentation Pull Request

## Description

Changes to portal VM creation: all in one step

## Type of change

Please delete options that are not relevant.

- [x] Incorrect Documentation

## What has to be reviewed

Section `docs/services/virtualmachines/docs.md`

## Checklist

- [x] Documentation follows the project style guidelines
- [x] Self-review of documentation using mkdocs on local system
- [x] Spellcheck has been performed
- [x] Pre-commit has been run and passed

### CODE REVIEW

**Comment by jhay-epcc** [comment]
Looks really good. My checker is complaining about multiple consecutive blank lines at the bottom of the page:
```
1. The configuration job runs for a few minutes.


<!--
## Online support
-->
```
Once the extra blank line is removed, happy to approve!

**Review by agngrant — CHANGES_REQUESTED** [review]
Remove empty line on 116 - to pass pre-commit checks and then can be merged - as noted by JHay

**Comment by akrause2014** [comment]
Thanks, changes committed.

**Comment by akrause2014** [comment]
> Remove empty line on 116 - to pass pre-commit checks and then can be merged - as noted by JHay

Done.

**Review by jhay-epcc — APPROVED** [review]
Sorted, thanks!

**Review by agngrant — APPROVED** [review]

**Pull request merged**
