### PR TITLE
Update L1_getting_started.md

### PR DESCRIPTION
**Pull request by adrianjhpc**
Adding in indent to generateName: as without this the kubectl create fails.

# EIDF Documentation Pull Request

## Description

Updating K8s script in documentation as currently fails.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Incorrect Documentation

## What has to be reviewed

L1_getting_started.md

## Checklist

N/A

### CODE REVIEW

**Review by edinburghadam — APPROVED** [review]
I agree that these changes improve the documentation, and in particular the indentation error which causes a hard-to-parse error.

**Review by agngrant — COMMENTED** [review]
Which webpage should they request a VM through?

fule -> file?

**Comment by DimmestP** [comment]
This pull request is now stale following #135 and can no longer bu pulled in as is. The suggested changes and fixes to the documentation have been included in other commits. Please delete this PR @adrianjhpc / @agngrant / @edinburghadam .

**Comment by agngrant** [comment]
Pull Request #135 has rendered this stale. As previous contributor noted updates have been incorporated in subsequent commits.

**Pull request closed without merging**
