### PR TITLE
SSH Key Instructions Added

### PR DESCRIPTION
**Pull request by awat31**
# EIDF Documentation Pull Request

## Description

Please include a summary of the change and any issues being addressed.

Please also include relevant motivation and context.

List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Incorrect Documentation
- [ ] Incomplete Documentation
- [ ] Missing Documentation
- [ ] Formatting
- [x] New Documentation

## What has to be reviewed

List the pages/sections that are to be reviewed.

## Checklist

- [x] Documentation follows the project style guidelines
- [x] Ensure Contact details contain Service Emails and Numbers
- [x] Self-review of documentation using mkdocs on local system
- [x] Spellcheck has been performed
- [ ] Pre-commit has been run and passed

### CODE REVIEW

**Comment by akrause2014** [comment]
This only shows how to update and add keys in SAFE - preferably it should document how to do this in the portal.

**Comment by awat31** [comment]
Added how to add ssh key in portal. 
Included safe bit as an extra.
Any issues please let me know as I had to do another pull to commit this. looks like I've only edited one file but just want to check everything else is okay :)

**Comment by nickaj** [comment]
The EIDF-Gateway is a method of accessing EIDF Services through SSH for a terminal experience.
It's not THAT bad!

**Comment by nickaj** [comment]
It might be nice to throw in a screen grab (suitably photoshopped to remove any personal info) of a correctly added Key in the portal, so users can see what looks "right".

**Comment by awat31** [comment]
Updated to include an aimge of what SSH key should look like

**Pull request merged**
