### PR TITLE
AG: added specific FAQ to the GPU Service

### PR DESCRIPTION
**Pull request by agngrant**
# EIDF Documentation Pull Request

## Description

Addition of a specific FAQ for GPU Service. This will expand to include specific issues encountered via user feedback and other problems or short term workarounds.

This will avoid filling the main FAQ with GPU Service information.

## Type of change

Please delete options that are not relevant.

- [x] New Documentation

## What has to be reviewed

services/gpuservice/faq.md

## Checklist

- [x] Documentation follows the project style guidelines
- [x] Ensure Contact details contain Service Emails and Numbers
- [x] Self-review of documentation using mkdocs on local system
- [x] Spellcheck has been performed
- [x] Pre-commit has been run and passed

### CODE REVIEW

**Review by akrause2014 — COMMENTED** [review]
Makes sense to have GPU Service specific FAQs.

Should this be included? https://github.com/EPCCed/eidf-docs/pull/108

**Comment by agngrant** [comment]
> Makes sense to have GPU Service specific FAQs.
> 
> Should this be included? #108

I think if this is merged, #108 could be asked to append their changes to the GPU Service FAQ

**Comment by nickaj** [comment]
Agree with @agngrant - #108 should be based on top of this new page.

**Comment by akrause2014** [comment]
Fine by me.

**Review by nickaj — APPROVED** [review]
Fine to merge

**Pull request merged**
