### PR TITLE
AG: updated with reverted base and changes from prior pull request

### PR DESCRIPTION
**Pull request by agngrant**
# EIDF Documentation Pull Request

## Description

Incorporation of Gitlab Documentation for the Container Service created by S Haynes into main EIDF documentation.

This is to prepare for the launch of the container service to a wider audience.

This is a reiteration of the prior request that was reverted.

**Hold until any name changes are finalised**

## Type of change

Please delete options that are not relevant.

- [x] New Documentation

## What has to be reviewed

Container Service - Overview
Container Service - Tutorial

## Checklist

- [x] Documentation follows the project style guidelines
- [x] Ensure Contact details contain Service Emails and Numbers
- [x] Self-review of documentation using mkdocs on local system
- [x] Spellcheck has been performed
- [x] Pre-commit has been run and passed

### CODE REVIEW

**Comment by agngrant** [comment]
Updated to name of service: EIDF GPU Service

**Review by akrause2014 — COMMENTED** [review]
Small comment: The folder is still called `containerservice` - it doesn't matter but you may wish to change it now if you care!

**Review by akrause2014 — COMMENTED** [review]
Another small one. The second sentence in Overview :
> Full Nvidia A100 GPUs are either connected to 40GBs of dynamic memory.

Either what?

**Comment by akrause2014** [comment]
The numbering in L3_running_a_pytorch_task is not correct. All paragraphs are numbered "1)"

**Comment by akrause2014** [comment]
I'm getting 404 not found here:
https://github.com/EPCCed/eidf-docs/blob/main/docs/training/resources/example_pytorch_code.py

**Comment by agngrant** [comment]
Updated with fixes for comments.

**Pull request merged**
